# Deployment of the Example App: https://github.com/skupperproject/skupper-example-hello-world
- name: Ensure Camera App namespace exists
  ansible.builtin.shell: |
    kubectl get namespace {{ app_namespace }} >/dev/null 2>&1 || \
    kubectl create namespace {{ app_namespace }}
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml


- name: Camera App Backend Setup
  when: service_type == 'backend' or service_type == 'full'
  block:
    - name: Copy Camera Backend File
      ansible.builtin.copy: 
        src: files/camera-backend.yaml
        dest: /tmp/camera-backend.yaml
        mode: '0644'
    - name: Create Camera App backend ConfigMap
      ansible.builtin.shell: |
        kubectl apply -n {{ app_namespace }} -f /tmp/camera-backend.yaml
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Expose Camera App backend service # Do it this way to have variable name of service obvious in Ansible.
      ansible.builtin.shell: |
        kubectl expose deployment camera-backend \
          --port=5000 --target-port=5000 \
          --name=camera-backend-{{ instance_name | lower }} --type=ClusterIP -n {{ app_namespace }} || true
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml


- name: Camera App Frontend Setup
  when: service_type == 'frontend'  or service_type == 'full'
  block:
    - name: Copy Camera Frontend files
      ansible.builtin.copy:
        src: files/camera-frontend.yaml
        dest: /tmp/camera-frontend.yaml
        mode: '0644'
    - name: Create Camera App frontend ConfigMap
      ansible.builtin.shell: |
        kubectl apply -n {{ app_namespace }} -f /tmp/camera-frontend.yaml
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
